apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-back
  labels:
    app: dep-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dep-back
  template:
    metadata:
      labels:
        app: dep-back
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          ports:
            - containerPort: 8080
          env:
            - name: "HTTP_PORT"
              value: "8080"
